enum ActionTypes {
  LOGIN = 'AUTH/LOGIN',
  LOGOUT = 'AUTH/LOGOUT',
  FETCH_HOTELS = 'HOTEL/FETCH_HOTELS',
  SEARCH_HOTEL = 'HOTEL/SEARCH_HOTEL',
  GET_HOTELS = 'HOTEL/GET_HOTELS',
  LIKE_HOTEL = 'HOTEL/LIKE_HOTEL',
  SAVE_HOTEL_ID = 'HOTEL/SAVE_HOTEL_ID',
  REMOVE_HOTEL_ID = 'HOTEL/REMOVE_HOTEL_ID',
  UNLIKE_HOTEL = 'HOTEL/UNLIKE_HOTEL',
  SHOW_PRELOADER = 'APP/SHOW_PRELOADER',
  HIDE_PRELOADER = 'APP/HIDE_PRELOADER',
  ON_RATING_FILTER = 'FILTER/ON_RATING_FILTER',
  OFF_RATING_FILTER = 'FILTER/OFF_RATING_FILTER',
  ON_COST_FILTER = 'FILTER/ON_COST_FILTER',
  OFF_COST_FILTER = 'FILTER/OFF_COST_FILTER'
}

export default ActionTypes;
